---
abstract: 'GenOO framework extension to read SAM files created by the BWA aligner'
author:
  - 'Emmanouil "Manolis" Maragkakis <mns.marag@gmail.com>'
build_requires:
  Moose::Role: '0'
  Test::Class::Moose: '0'
  Test::Class::Moose::Load: '0'
  Test::Class::Moose::Role::AutoUse: '0'
  autodie: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: GenOOx-Data-File-SAMbwa
requires:
  GenOO::Data::File::SAM::Record: '0'
  Modern::Perl: '0'
  Moose: '0'
  namespace::autoclean: '0'
resources:
  bugtracker: https://github.com/genoo/GenOOx-Sam-BWA/issues
  homepage: https://github.com/genoo/GenOOx-Sam-BWA
  repository: https://github.com/genoo/GenOOx-Sam-BWA.git
version: 0.0.3
